name: 'Gitbook Action Build'
on:
  push:
    branches:
      - main  
env:
  source_branch: 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        source_branch: main
        publish_dir: /docs
        gitbook_epub: true
        #gitbook_epub_dir: /docs
        #gitbook_epub_name: 6S081
        publish_push_force: true
        #publish_token: ${{ secrets.PERSONAL_TOKEN }}
